group=me.earthme.lightingluminol
version=1.21.8-R0.1-SNAPSHOT
mcVersion=1.21.8
release=2
# 0 for skip release, 1 for pre-release, 2 for release

luminolRef=754de8c0b63d70604aa6ac7f4399e1b0fd9c1838

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
