group=me.earthme.lightingluminol
version=1.21.8-R0.1-SNAPSHOT
mcVersion=1.21.8
release=2
# 0 for skip release, 1 for pre-release, 2 for release

luminolRef=27a232a7d8669bffc808aa9cebb7f2fcaa9d8b62

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
